name: .NET

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  Build:

    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [
            Release
        ]
        solution: [
            src/Skylark.sln,
            src/Skylark.DNS.sln,
            src/Skylark.Wing.sln,
            src/Skylark.Uptime.sln,
            src/Skylark.Standard.sln,
            src/Skylark.Clipboard.sln,
            demo/Skylark.Console.Demo/ConsoleDemoJs/ConsoleDemoJs.sln,
            demo/Skylark.Console.Demo/ConsoleDemoCss/ConsoleDemoCss.sln,
            demo/Skylark.Console.Demo/ConsoleDemoTax/ConsoleDemoTax.sln,
            demo/Skylark.Console.Demo/ConsoleDemoUrl/ConsoleDemoUrl.sln,
            demo/Skylark.Console.Demo/ConsoleDemoWeb/ConsoleDemoWeb.sln,
            demo/Skylark.Console.Demo/ConsoleDemoXml/ConsoleDemoXml.sln,
            demo/Skylark.Console.Demo/ConsoleDemoHash/ConsoleDemoHash.sln,
            demo/Skylark.Console.Demo/ConsoleDemoWord/ConsoleDemoWord.sln,
            demo/Skylark.Console.Demo/ConsoleDemoJson/ConsoleDemoJson.sln,
            demo/Skylark.Console.Demo/ConsoleDemoHtml/ConsoleDemoHtml.sln,
            demo/Skylark.Console.Demo/ConsoleDemoPing/ConsoleDemoPing.sln,
            demo/Skylark.Console.Demo/ConsoleDemoPort/ConsoleDemoPort.sln,
            demo/Skylark.Console.Demo/ConsoleDemoText/ConsoleDemoText.sln,
            demo/Skylark.Console.Demo/ConsoleDemoTime/ConsoleDemoTime.sln,
            demo/Skylark.Console.Demo/ConsoleDemoSpeed/ConsoleDemoSpeed.sln,
            demo/Skylark.Console.Demo/ConsoleDemoColor/ConsoleDemoColor.sln,
            demo/Skylark.Console.Demo/ConsoleDemoXhtml/ConsoleDemoXhtml.sln,
            demo/Skylark.Console.Demo/ConsoleDemoHelper/ConsoleDemoHelper.sln,
            demo/Skylark.Console.Demo/ConsoleDemoUnicode/ConsoleDemoUnicode.sln,
            demo/Skylark.Console.Demo/ConsoleDemoLottery/ConsoleDemoLottery.sln,
            demo/Skylark.Console.Demo/ConsoleDemoStorage/ConsoleDemoStorage.sln,
            demo/Skylark.Console.Demo/ConsoleDemoPassword/ConsoleDemoPassword.sln,
            demo/Skylark.Console.Demo/ConsoleDemoCryptology/ConsoleDemoCryptology.sln,
            demo/Skylark.Console.Demo/ConsoleDemoTypography/ConsoleDemoTypography.sln,
            demo/Skylark.Console.Demo/ConsoleDemoTemperature/ConsoleDemoTemperature.sln
        ]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        dotnet-quality: preview

    - name: Restore the Skylark
      run: dotnet restore ${{ matrix.solution }} -p:Configuration=${{ matrix.configuration }} --configfile NuGet.Config
      env:
        NUGET_CONFIG_PATH: ./NuGet.Config

    - name: Build the Skylark
      run: dotnet build ${{ matrix.solution }} -c ${{ matrix.configuration }} --no-restore /nowarn:CS0067,CS0108,CS0109,CS0114,CS0169,CS0414,CS0649,CA1416,NU5104,NETSDK1138,SYSLIB0003

    - name: Test the Skylark
      run: dotnet test ${{ matrix.solution }} -c ${{ matrix.configuration }} --no-build --verbosity normal
      env:
        NUGET_CONFIG_PATH: ./NuGet.Config